[server]
headless = true
port = 8501
enableCORS = false
enableXsrfProtection = false
maxUploadSize = 200
enableWebsocketCompression = false

[browser]
gatherUsageStats = false

[runner]
magicEnabled = true
fastReruns = true

[client]
showErrorDetails = true
toolbarMode = "minimal"

[theme]
base = "light"
primaryColor = "#CC0000"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F5F7FA"
textColor = "#1a202c"
font = "sans serif"
[logger]
level = "info"

