[server]
port = 8502
address = "0.0.0.0"
headless = true
runOnSave = false
enableCORS = false
enableXsrfProtection = true

[browser]
gatherUsageStats = false
serverAddress = "freemobila.duckdns.org"
serverPort = 8502

[theme]
base = "light"
